language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - 3.4
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  # webapi key
  - secure: EGhmZm/vFU9Hh/3Rybbe/z22w6IEKp9OSL23OXpNQw0YBbbbJsBl6XhiZcCNypTCOBGwRFoRJcBq+L33TVxsOFMOXzXmXCpM3x9rWnad2QGlaF5qT9KKaU06Sn3s1c8s0o/cHf0q9qeN/ncfIH4qQ9wpK5/FaEpsJ8Sdol0cXgjH+/BfCt4joPq2ujiWVPXK0oQ2vz6mBCaa03OGoz3+tcThXA66IghkBw719/1Wmrdf4P5AczOTyUQr055fMc8RtllWozFcTSIFWLCHXrgPaTR5AONGTt9n/szDngxSO2DQWQbllhb/0wo38WPayiWJ8HAW11thq8Npg6wXHQjesZXGgWOjPq12t0a/QH+qLxC3oa6njrrTBdH+CelnkKrA2h5CzoREbxrG8NiFxc2LdVgf2WcPCYBqJFOPHTZS8DZApm+jJ9kSNsZ2UTZvcsHqpkflUqPTRjq+IUlVSYIj4/SsisZo00gVujJ9LZf7SHcImriKZ1ogsTz3uxwKu/8zFEWGDnAvwut4kQGwTXI6jdnXjX+FfakNANZjxwnqCMqyMSa5mZ+owYOUlSHLd/+8+KeRTapm8efRnx7OHbDGciFlgOV3vWQ9stdDBkqC7ZrAgY/NcpafI22NBphJTTem6pJJcGRgSKQedbYP6InCG/K/ZZlVmKLICdwIWMSQtJA=
  # cds key
  - secure: mCIR7qsGTKaqTCHNEZkcEBzf0oqBI1o0szgKrOY8EyOb8l8ByPYjpn8KWa2nLnctYDVLarm2NBcIyWD56ehMeKO8CC3xmwmYZMOrfBNUS+s85E6zy9cnn521wAvq3LztiYwuLM76O0CD9MVBxfUKFOlececlfX7dkzsRWi7NWYT3tERyDr7axiVxhkAfawNUD3l/rSnCouL9er9cOMs3qTfq9PDMh7CxM5IKvWzJu16HNtC5JV2TqNWkGyeIiinULK3TfkNiMjBYAeP926le/oVIZmMcAvmX52+GT9ZUpnGREAUuhUdjOJw8JwpNOIlcmQwipujXFAp2ew0ok6UlkVaLURyq/vMH43fnjKa8mqQRfQ0Nd22qQY+NHyry+afVfG/c1F7I8jStPn3GDZqo8dyjoctg7bn17GnqwZsXDzNd74RObDtqqHfZIxsgNk0EV+A3RwDqBVG9J0YCJFeVgSDFMjRlUvqzlw1rXtUDcgdgkRhNkv6Zfnc44mxCwCb0RaFmMS33GIvl9UlCoAaoZutbdm2TcYt6pSugkl/a8M7lnNkJS8izWB3rtBIFoqYuWlp++XnC5YyRA22HFr6mG+WA7+HFKsag4ubs02LS3nzq79pBt1yGxQ/y+6lGq8WhfdUbW8kpTzsc2G5uYTMw/UlVT6+iPaLSsPJ/VGdortE=
