language: R
sudo: required
cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get install --yes udunits-bin libudunits2-dev libsodium-dev

r:
  - release
  - devel

r_packages:
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
