language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    # webapi key
    secure: "eV2EfUPSJOJqBKFq8kYCjgfluYlrg7ycPkB52FdniH4XY0KKR6LhBDcp+ZpxYAlIqGV3aDIKJ4BDFIhakceuPVnORimrF2sl61D+f4hbnSQMi5JmcQP6VrvvOhpFMai4uAOKFaKmT34QMloPtpRGKDxd7b2gCnEHoy0g82MKbRDeQApeNmHcTe+8TGDlp0qD2Sx75eucBSf2wn1vstq+XIlFj0SYoRPUY3QZvWFJ11y2Ko8tpTttC7gyxIOcTqkM/IPH16o9YXpuoI0NCO60XVWYd/VuncjdQjlgBlgwayYdLmSUTaGCvbHWZo/dG80yO9egP5QVqlp3XS9V5q6jyzzOjhBtRFo0Eqd1rx/QPmVRetK6Y5V+UhI2lWRkBr9tdJ8PknvReNYdN2sqwFwC7WmyvxYxD4+NNtDHY40QLF1fcK20GkHPgdQskGk4W8QkADsa1SZoZmwcgTfDo0TB13VNwRFVYEajoqzyd/LFO66Z/iGm2Y6m5ZgdLi+NRjhrjq+bC4neKTaXHmEMrKsGOIa5uGrmh+t0Lbu6rBfaTN8cLzKf0o7EMBZ51aBw7jZQahUSFA095a3wHgF/QsKpD5L+BIjhJ2XPLGhgHWcvrkTUC+DdNQUz3WvI6WDhF1ryNBYosrjAUYeqGw2xRjwNNMWywOwXy/+JxKi/Vk/0t58="
    # cds key
    secure: "RuYdSxcxFs0uV4QSOwk9FOF7QJTeiDXadoU4yNwSlvnKe1OSXriHZ0luVacj1qaF/PPEOw697+21g60pzxqYD2RSSPUMIuIv5akABprJOquLTF8iYDuhJrDUQfJCm7xaK87TKNiJwW4YME2EFqIXl8tw5TcV8/we8FVUyDSSxB74EzhE5WlziVJdQ5V5TzfNCu0gsy1JJWfgJ0IseNnmoT2gQER4jbZcSSMNSSRIZ0ddz6s2T52R8RREH3AIULg0M4XDh0p4WKnF3IitfGiBj+pWSQmp0VmtwZnomGQ08/vQaCPX+MG6vMLojdUeG4BLKgHIysv8ac3PfJZO8IBxMzXSTcaSYjn0DvHioE2bzVmKExKlte9D84lvPlYQx34oWeTBfn5Evw1o3dRx6a7yV0jAYBueCWV+Sn4QkiN8djzf/BfwcSnCs/3Q4g7bXRdrCxZO3oPKLKm1mEhrdN2gWCj7TTlvvQmflMEhn+tT0UsDViAbrlMAW68l00HyAaYyRtPJr9zDwXNT/guWA9qumKG/ymWcbcBKjXunXi/2ZEN7px9ZkXFUk8A45itwEJ6AybIpx7qq6ZWK67KKdT3jcYxOHthunrVzwiPe8YwCp4YbUPf4XX1d/EuI/XDoonZr+Jl7fUaXXBJzYuGmK5tLdhOO1+Tc/YvQsE2weDIduAQ="

