language: R
sudo: required
cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev

r:
  - release
  - devel

r_packages:
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
