language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  - secure: EGhmZm/vFU9Hh/3Rybbe/z22w6IEKp9OSL23OXpNQw0YBbbbJsBl6XhiZcCNypTCOBGwRFoRJcBq+L33TVxsOFMOXzXmXCpM3x9rWnad2QGlaF5qT9KKaU06Sn3s1c8s0o/cHf0q9qeN/ncfIH4qQ9wpK5/FaEpsJ8Sdol0cXgjH+/BfCt4joPq2ujiWVPXK0oQ2vz6mBCaa03OGoz3+tcThXA66IghkBw719/1Wmrdf4P5AczOTyUQr055fMc8RtllWozFcTSIFWLCHXrgPaTR5AONGTt9n/szDngxSO2DQWQbllhb/0wo38WPayiWJ8HAW11thq8Npg6wXHQjesZXGgWOjPq12t0a/QH+qLxC3oa6njrrTBdH+CelnkKrA2h5CzoREbxrG8NiFxc2LdVgf2WcPCYBqJFOPHTZS8DZApm+jJ9kSNsZ2UTZvcsHqpkflUqPTRjq+IUlVSYIj4/SsisZo00gVujJ9LZf7SHcImriKZ1ogsTz3uxwKu/8zFEWGDnAvwut4kQGwTXI6jdnXjX+FfakNANZjxwnqCMqyMSa5mZ+owYOUlSHLd/+8+KeRTapm8efRnx7OHbDGciFlgOV3vWQ9stdDBkqC7ZrAgY/NcpafI22NBphJTTem6pJJcGRgSKQedbYP6InCG/K/ZZlVmKLICdwIWMSQtJA=
  - secure: ac8UeRMBi9qXoXStVkS4qeAjo4XFE4T/29hmrBPtdrbrvh4k9oui2u5NdYzm+mN0AiQ4NjyXSImfs+x1k05yL0gjGeSBlLVt1M//FiS/VngmDm8G6FOL93bCrm/yeMNm7i0iOGIrjhHw3lZIgpzg12l8KkhBeVQ4mIspvZx3xi4JHYYBNgXs7/UE5LaT7275y4NVxpC25B4MkrZGPzN3R7FLc0kIpheBRZbfVmjXYyUHTExfjwNzNB2lI3C1G862LsbSht9tqeERUs+3nNqJz29YDb1VedyrVWcP41pYnFFg8ac5ZTzQikhEtZorMvsTdOTXvIbIbxMq+HyqVB4OWoY8aXupeeCXaczwarigcVRIvGg/Ho7MBnT1g/2ta7bPFYTPGab9Sdc2lhVYjkBtPGWbxqAPSJYnuDUYuGcBUvZgPxkw892Fu33pUPZvMcDnz9gaG/NslNFsyfexUJtD9UCbFIhid628ZIBSpn9ffc0I+cwMLJqPyIncvas6TcTpe75w2nn2KnU7PQFwcfBEzeO4kZbH/ggkz8bwPg8l7ruPlJ9SE/7sxTajje3Bemo25ofoA6gFFX9e7z64Q7i3xsSdkyYpAcaif+qpUpZFsd6gJ6vYbszjHx6ijLn5Z8wkLc2CCPFahJLy1UqgCa/mYny0aBD2rrJP0DK5DTSkB0k=
