language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - secure: JXh+52sqTYKd6EIaMKsZVVIq6EuSvOhOQUei8GMPX0K1DfjF1CXAcL1Shcieqmtb5LklHTIvyQlaI4hY8Rejfj3Q+KC+H8q9j3bn+cVrQIox7hAAUCjJfzwjTC90Bh/mEe1LKW1IMbftAHedHSjz4lpqG7YsZrZLy/HXsJH9iKyPctJNYnT7jwmMlwEJLm+1wvHVnvbEqICagbCu2WWf3qieTpqTx/4yU6FGBZ80opf8Xvp+RS7jPmn4K9hz+6YP8z7nS4hWMsHeYceDC/HqdofHkEBWa9pBXKg83rKMlVBqzTYGqULa+1mA+wd4XnSr3toEGQ7AibmlBxtY12iGJ/Vr9uW0rKp3yF5Po0mW5DyyYGQINf4qLo2KiDeDwCS3uzc7P7bVVeZUK++/bUvuailZplJKH8pllh6gyAl+yz3M410C53MiZ3hv2NquJSxiEVgusVt5Nl0ev9t2pzMORzkLIc+Iz+R7+xN0KFvxiK04xreuej1QaqjvSmAtciHzIudCVjCXnF8AxLnKZAjVjJvZ8DoR3ozqTEXDXsNNh+x0/NMPS92EtvcOmh1w9b4dfXsMGQnUbr8mcE027FzWR6GN69ezD0cqsmDZWGbFf7ExnhubfLCisHeSrcJ1DYHSB5YUw3pdJLgcQSKCJ2Pq/7tXyHQsZJ0lE40wQQwcPBg=
    - secure: GUBi08RbYi0KNQGR2pxTDKPBeF/3uV0SmlEEZPHm5teN+zf4+17W/icsVGhMpNqOO9PkrugivifE8C6vyussirzqsER2JDCZmYrjH+Ul6PtVuidIb/ws94b489B/XybsPkCDVC/iPAMekkkH05Vccid5F8PQKCOcvSEiZcRoU/kj+pVc1Az+tCecGVPZjBIN7YcY0zHs6qD5uC4e2H+me6SnyCj8yJ2f3aISGIXKrXiW9o5pQQ/sCWdubHpc9ai28LB/IcER9qM2+0PrBHBYiblIwa8ycG60yzEzgexTz4TKN6xAyFVr6+JI7UUuH0Y1dwUf32xMvXDchq7yLc9Gx8DMBGLh89d7dT+PtxNBu+SXNEy3ELfVpmuBS1Yub16KWTIeisHNzVfwvYCGIqU2sN8ZpuEYjx9GKkaU0hpKDQM53MxK3rrTEsuC+dus/QF6NGWAIuwKsAx71QImOLLRsEBRtnKZWbNnFhzg8qtK4Rj/ehIb1Rjq2a9tUQBqVVFfPkNn7XzhXxd9fni2n9SLRBYL5v6x4nXxGTcb6vdj6jekaX6TSVNBr1rsd7AmoQn6x7iX+meD06lDUVz8Q0pyeNHCkKWU7U6VpcEiNIyd5uE/+Fc1nXIqjSMziJxvUC9fEfb2P09HYYbMHfQ2zKTM9izzLXDhjx4neFWsQ1RWeys=
    - secure: XyuE5DzheFMr2bktw2z5kYPCrRhlYJjxlZ6GlHkAG6U+O7xDfr4GmAsFnHErIWxr3SneO7IOYzzahxQrvPu26IUcQMobMnK4HmxWaWX98hykPs0RNX9xeV6wDPPPy61xjc/mxj9R7+XiVf9w1dzKNZY0HnRNGL9DZWAQZ7dUxB8Z09OXtWiNN4JV0ZGRaRJBmRSB1Ilf1b7ZG37mN/Y7PXIFwd3KGkvQswI+YL1WESpb0CpDa9xfiAY9SzL4rhuaMYLM0YP2+kqsSe+5mjfoAjukNBQgfAZ5SRGnQPD1mE/7acZLj0YyVyWphP8tlFI0uOlQfe2PyqmLJfScttJyLdmrVqn408KVLI/kLSvwIbzFCOTfo/gcGuwf/RcVr6h3St0BnVW7vURJV9clobf8ALMqFMveEd0VwJgOTiDNMdEEuhF64+36EKnANXlEsRk8EVseZorYkkMfNmdFZv08QPkufmnmslqkVAMZKJuaL9aHro8kQ4gS0cq22eSHenXx1Lx9i15D3tNG7NoN7YJ/bZxPwf7n7aRoecHbphwLVEsMiPqjSbTxceWQrLCXk2j6drgjcMEGQxmIkgqOxBqJDd2D2sX+nmzNOyukRt90nZf+IX6JBQ5yuLmhB5el/yTeR8oSEr8OKmqaiPWzcBxIwN6zRqOrzXmu3N/ncRm2OD0=

