language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - secure: JXh+52sqTYKd6EIaMKsZVVIq6EuSvOhOQUei8GMPX0K1DfjF1CXAcL1Shcieqmtb5LklHTIvyQlaI4hY8Rejfj3Q+KC+H8q9j3bn+cVrQIox7hAAUCjJfzwjTC90Bh/mEe1LKW1IMbftAHedHSjz4lpqG7YsZrZLy/HXsJH9iKyPctJNYnT7jwmMlwEJLm+1wvHVnvbEqICagbCu2WWf3qieTpqTx/4yU6FGBZ80opf8Xvp+RS7jPmn4K9hz+6YP8z7nS4hWMsHeYceDC/HqdofHkEBWa9pBXKg83rKMlVBqzTYGqULa+1mA+wd4XnSr3toEGQ7AibmlBxtY12iGJ/Vr9uW0rKp3yF5Po0mW5DyyYGQINf4qLo2KiDeDwCS3uzc7P7bVVeZUK++/bUvuailZplJKH8pllh6gyAl+yz3M410C53MiZ3hv2NquJSxiEVgusVt5Nl0ev9t2pzMORzkLIc+Iz+R7+xN0KFvxiK04xreuej1QaqjvSmAtciHzIudCVjCXnF8AxLnKZAjVjJvZ8DoR3ozqTEXDXsNNh+x0/NMPS92EtvcOmh1w9b4dfXsMGQnUbr8mcE027FzWR6GN69ezD0cqsmDZWGbFf7ExnhubfLCisHeSrcJ1DYHSB5YUw3pdJLgcQSKCJ2Pq/7tXyHQsZJ0lE40wQQwcPBg=
    - secure: GUBi08RbYi0KNQGR2pxTDKPBeF/3uV0SmlEEZPHm5teN+zf4+17W/icsVGhMpNqOO9PkrugivifE8C6vyussirzqsER2JDCZmYrjH+Ul6PtVuidIb/ws94b489B/XybsPkCDVC/iPAMekkkH05Vccid5F8PQKCOcvSEiZcRoU/kj+pVc1Az+tCecGVPZjBIN7YcY0zHs6qD5uC4e2H+me6SnyCj8yJ2f3aISGIXKrXiW9o5pQQ/sCWdubHpc9ai28LB/IcER9qM2+0PrBHBYiblIwa8ycG60yzEzgexTz4TKN6xAyFVr6+JI7UUuH0Y1dwUf32xMvXDchq7yLc9Gx8DMBGLh89d7dT+PtxNBu+SXNEy3ELfVpmuBS1Yub16KWTIeisHNzVfwvYCGIqU2sN8ZpuEYjx9GKkaU0hpKDQM53MxK3rrTEsuC+dus/QF6NGWAIuwKsAx71QImOLLRsEBRtnKZWbNnFhzg8qtK4Rj/ehIb1Rjq2a9tUQBqVVFfPkNn7XzhXxd9fni2n9SLRBYL5v6x4nXxGTcb6vdj6jekaX6TSVNBr1rsd7AmoQn6x7iX+meD06lDUVz8Q0pyeNHCkKWU7U6VpcEiNIyd5uE/+Fc1nXIqjSMziJxvUC9fEfb2P09HYYbMHfQ2zKTM9izzLXDhjx4neFWsQ1RWeys=
    - secure: XicSbgD5De2cNVh55tzXIRga2zFrWxU5rIx2mkAV7ksc6ZIajsJBpDTa5+rmGztwvY0J+3rISzJ1SXueGKpA0rndCs6+38Z32kaMBDu/1j6GxZPr1c5a3XkpInDdJd6OVVXhxRCK16pgcOr8M/PpOPkfmwxyxADMMhbXy8kV9wctO8jQM5F8PjhQWndY6VTwiCpJ8gXMNWezoghzXXScOcOhFNDShuGyYxOELk3X5euW9DTQtQrXWIl2iQTmt8OPOgyYWELjCcLLlkcwhhC1VjdQq6yL8EcS8tT01OuScyA0neeudZPiyoIbYX6XRmThuxmS9ruejrLpuRUGXeQbAB362NGRgKG32KBSds2BvRWTc8yWxPdMc7FZ11ifgat50MYXl9OVd1tmVnSfN38U+RDk6VQ28k3norWgbiB36tL2+1IMj+D5XxCeXQoaHjvKcM6Zhbr/4Qqm4TYq9agPNm5szRr/KrbZvu84kzNC8Vly8wv/RX8BqhZ2A2scsBuRpF2cUmwrpZeYjCzSUs5F2vrLHc/5fCX5UK5ZNfVoOK9YP15kY5VwuSi/Jhp5Ttzs7mnbg21IFPDVUiq+hpQezZEGk3cKrEX4TdO65jeY7fD1RCvVs079ebKMIu9FxPPS+OVCB8zn/zIWMagV+uEglncskdLReVvQm+kIVKqcYwk=

