language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
  # webapi key
  - secure: eYmphxZxnJyfhOtZaxgvuYGfWk+UMbqwdFE/e6chtYz8H0UvGuM4CkvgKJ7dv++CWaeujayJySPRjuxREb3haGT9LSgVC0KfWN/xMms5DJLKMb0vWfrb+q91cWngvg5Xu3yBOo2hi6O8d0Mx2wgD/ZK3x1D3nyWpjhoU4pK6FSCaT86q9IM4MNAUJsGDTnuV2lEINa+ck2pwVfUy5vWye75PnI9x930zk4DN6uSKuCADLHDiVOcHFnC1fo2zxFnmXQcgWgYmUBdxTRU38g5Z73U9x6pGGUA7EipmG1zsiXxb279NaNs/7cIzoC56NpFNLrYNcq/Q8k6KMF3hK1BUB1b45jUOQl+x20Iorh5Q3R9qQJoqaOkwlbyPO6nrnHbOS2uWgCpOD5UzSWqfhZm7I//3Pk6VUbEYr8xEfr8rqDlsimMMrB4lhiwUwN3lVvdje8w3VOP+bPS2/5Lbpas+tHMvdh6sXEJGMFaZIV/jfjcpDrzR32Yd/09wbeQCSfgLcYD8JRxuBI1JGjpkuxwMUvNuKpryx59LWd48cF18Yv1F0Rr/oS7kz0IrSXp110jB25j4YexpZAaVj2rx/qwjWbubAuS5evEwEwoqBis3FM2LN8pbOSUAdBkcRDiM/goeItlMkoNRLMk1Tpr73iJ3YYXUb9lC6e3SL5Vm1pJXapA=
  # cds key
  - secure: nPjp3LZsLjohX/E+yLYYQAr1Qf/cd6Xks4G9cm2Hk8Duk9C9CdHXxqGLlO/C2cYk3jHZZevLIpqrjcCY2Rk1qs+H1c88H3r2Icd1oSwkhetgkjvgLR/2W2Sy0D5udzQhW6vlTh7sqzYKzMcfAkGmxi3nnAwKbsCnV0CbegETC5ePzlhbGmDgTfEl3ey8BLMoFJSDlKW7H3gMQ0aSsZ8DPnHkzGXRQl8TduLr+vRajgnn02r2we7eB2ODiaN8YEMyNLDg8g9/nc5V3WYnrc87HFun/pi/0EACt5FQevDBizHw9ZsQpYDRf9nfbGx0Lo2iD8ESd1cUiTIUGzXrENqZyszwx9f72i/bXRuiZv7DO6fojK0+ijlPMkRE+YsA7sgSfBsru6uZ+xALe++FxOP4XDL2LskauVC8xZCpmrmDVjCMLwVx/mSfI5pnwFb5DE477HfJOVTim3MbMbL/1Fea7eg2nawHidrDyrnHtOTs8xUIRzcPNV2wKbcdQuVL+14VXMAbAX0zoy+T1/xmM/BN3HOug9GekwYlEUybD+LktZlVauhLP3/t93w3b52EygGUN4qh8Y+d40t+fiPtYYne4H5oiOt8rECqA1u9A8Xp+vMdYuvROeE5VYrRLvAW6ScSX4kb4v5xwmU2BPts8tLZ5JeaogZa6WfTkkKdV83me1I=

