language: R
sudo: required
cache: packages
warnings_are_errors: false
before_install:
  - sudo apt-get install -y udunits-bin libudunits2-dev
  - sudo apt-get install -y libsodium-dev
  - sudo apt-get install -y libproj-dev libgeos-dev libgdal-dev libgdal1-dev
  - sudo apt-get install -y libnetcdf-dev netcdf-bin

r:
  - release
  - devel

r_packages:
  - knitr
  - devtools
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

env:
  global:
    - secure: JXh+52sqTYKd6EIaMKsZVVIq6EuSvOhOQUei8GMPX0K1DfjF1CXAcL1Shcieqmtb5LklHTIvyQlaI4hY8Rejfj3Q+KC+H8q9j3bn+cVrQIox7hAAUCjJfzwjTC90Bh/mEe1LKW1IMbftAHedHSjz4lpqG7YsZrZLy/HXsJH9iKyPctJNYnT7jwmMlwEJLm+1wvHVnvbEqICagbCu2WWf3qieTpqTx/4yU6FGBZ80opf8Xvp+RS7jPmn4K9hz+6YP8z7nS4hWMsHeYceDC/HqdofHkEBWa9pBXKg83rKMlVBqzTYGqULa+1mA+wd4XnSr3toEGQ7AibmlBxtY12iGJ/Vr9uW0rKp3yF5Po0mW5DyyYGQINf4qLo2KiDeDwCS3uzc7P7bVVeZUK++/bUvuailZplJKH8pllh6gyAl+yz3M410C53MiZ3hv2NquJSxiEVgusVt5Nl0ev9t2pzMORzkLIc+Iz+R7+xN0KFvxiK04xreuej1QaqjvSmAtciHzIudCVjCXnF8AxLnKZAjVjJvZ8DoR3ozqTEXDXsNNh+x0/NMPS92EtvcOmh1w9b4dfXsMGQnUbr8mcE027FzWR6GN69ezD0cqsmDZWGbFf7ExnhubfLCisHeSrcJ1DYHSB5YUw3pdJLgcQSKCJ2Pq/7tXyHQsZJ0lE40wQQwcPBg=
    - secure: GUBi08RbYi0KNQGR2pxTDKPBeF/3uV0SmlEEZPHm5teN+zf4+17W/icsVGhMpNqOO9PkrugivifE8C6vyussirzqsER2JDCZmYrjH+Ul6PtVuidIb/ws94b489B/XybsPkCDVC/iPAMekkkH05Vccid5F8PQKCOcvSEiZcRoU/kj+pVc1Az+tCecGVPZjBIN7YcY0zHs6qD5uC4e2H+me6SnyCj8yJ2f3aISGIXKrXiW9o5pQQ/sCWdubHpc9ai28LB/IcER9qM2+0PrBHBYiblIwa8ycG60yzEzgexTz4TKN6xAyFVr6+JI7UUuH0Y1dwUf32xMvXDchq7yLc9Gx8DMBGLh89d7dT+PtxNBu+SXNEy3ELfVpmuBS1Yub16KWTIeisHNzVfwvYCGIqU2sN8ZpuEYjx9GKkaU0hpKDQM53MxK3rrTEsuC+dus/QF6NGWAIuwKsAx71QImOLLRsEBRtnKZWbNnFhzg8qtK4Rj/ehIb1Rjq2a9tUQBqVVFfPkNn7XzhXxd9fni2n9SLRBYL5v6x4nXxGTcb6vdj6jekaX6TSVNBr1rsd7AmoQn6x7iX+meD06lDUVz8Q0pyeNHCkKWU7U6VpcEiNIyd5uE/+Fc1nXIqjSMziJxvUC9fEfb2P09HYYbMHfQ2zKTM9izzLXDhjx4neFWsQ1RWeys=
    - secure: iflpT2GSyfvaQgslsaRkzfBDLovcHRMWvVnOz8RRHWO3VRejVtDHGBx+Nx5JXyJkJ9vEELF3eabTMKKo/7tXYt9n8ZS1mpvka/QhSbs+NowojkgO7NUH2CkIO8d3AuA7l1BhsM6CctbpPG6g+kGqx1H7qWN6+tjLXpN+bUCmkxgYiuJwxcdC3PHwweh6xEz9OmXB6wnzoi3bonxexcpW9DvVTaZruvJXkqvwGEvSt0silCUF0fWA5yTbemgWxG/BWeZlWYxwbbG9dSuHDhwmMErVtvjn+l5PTQDo7y7g3eSlDV1CZwWzqExD7GzEDa426k+W7jECHSe7z8thnPjplahEIQLK0zkclSMGBZgO3BvK/mAb+j+88l2ZfV5L4oN2fkcaGCLD0XfLfh4WR5GLSkPHTh1vPHiGK/0tf+egpAVbv1zoxiZfFAL0m9qFqOF/CGe8JbdnD+5N2uAesTk6nN8sCgsx0sY3qZv0RdOaEnJ4chBeHCnzqJ+dfv1QiuS7svCN/55u4mxrt6jAIMmr5gO4mby7H1vrOkAZT7yaOPdMhVuA6isI2bsRGTRADb4rnS/U4BxA+nUGgXYf3tTbh/b6pv8BqwAYws+9zrf7nEWvqAg6rPgASwcnD8AjvuhQkMvrIKjluvUgx++P1fbxzbEPiPckK8OQXE3RMCQ53rQ=

